version: '3'

networks:
  lamassu-net:

volumes:
  consul_server_data:
  auth_pg_data:
  enroller_csr_store:
  enroller_pg_data:
  elastic_data:
  fluentd_data:
  devices_pg_data:

services:
  ui:
    build: 
      context: https://github.com/lamassuiot/lamassu-ui.git#master
    environment:
      REACT_APP_AUTH_ENDPOINT: https://lamassu.dev:8443/auth
      REACT_APP_AUTH_REALM: "lamassu"
      REACT_APP_AUTH_CLIENT_ID: "frontend"
      REACT_APP_CA_API: "https://lamassu.dev:8087"
      REACT_APP_DEVICES_API: "https://lamassu.dev:8089"
      REACT_APP_DMS_ENROLLER_API: "https://lamassu.dev:8085"
      REACT_APP_CONSUL_API: "https://lamassu.dev:8501"
    volumes: 
      - './lamassu/ui_certs:/certs'
    ports:
      - 443:443
    depends_on:
      - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'

  consul-server:
    image: consul:1.9
    environment: 
      CONSUL_LOCAL_CONFIG: '${CONSUL_LOCAL_CONFIG}'
    volumes:
      - 'consul_server_data:/consul/data'
      - './lamassu/consul-server_certs:/consul/data/tls'
    ports:
      - ${CONSUL_PORT}:${CONSUL_PORT}
      - ${CONSUL_HTTPS_PORT}:${CONSUL_HTTPS_PORT}
      - ${CONSUL_UDP_PORT}:${CONSUL_UDP_PORT}/udp
    command: consul agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -data-dir /consul/data -config-dir /consul/config
    networks:
      - lamassu-net
    depends_on:
      - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'

  vault:
    image: vault:1.7.3
    environment:
      VAULT_LOCAL_CONFIG: '${VAULT_LOCAL_CONFIG}'
      VAULT_API_ADDR: '${VAULT_API_ADDR}'
    volumes:
      - './lamassu/vault_certs:/vault/tls'
    ports:
      - ${VAULT_PORT}:${VAULT_PORT}
    command: vault server -config /vault/config
    cap_add:
      - IPC_LOCK
    depends_on: 
      - consul-server
      - fluentd
    networks:
      - lamassu-net
    links:
      - "consul-server:consul.lamassu.dev"
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'

  keycloak:
    build:
      context: https://github.com/lamassuiot/lamassu-auth.git#main
    environment:
      DB_VENDOR: '${KEYCLOAK_DB_VENDOR}'
      DB_ADDR: '${KEYCLOAK_DB_ADDR}'
      DB_DATABASE: '${KEYCLOAK_DB_DATABASE}'
      DB_USER: '${KEYCLOAK_DB_USER}'
      DB_PASSWORD: '${KEYCLOAK_DB_PASSWORD}'
      KEYCLOAK_USER: '${KEYCLOAK_USER}'
      KEYCLOAK_PASSWORD: '${KEYCLOAK_PASSWORD}'
      KEYCLOAK_IMPORT: '/tmp/lamassu.json'
    volumes:
      - './lamassu/keycloak_certs/keycloak.crt:/etc/x509/https/tls.crt'
      - './lamassu/keycloak_certs/keycloak.key:/etc/x509/https/tls.key'
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
      - ${KEYCLOAK_HTTPS_PORT}:${KEYCLOAK_HTTPS_PORT}
    depends_on:
      - keycloakdb
      - fluentd
    networks:
      - lamassu-net
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'  
  
  keycloakdb:
    image: 'postgres:13'
    environment:
      POSTGRES_DB: '${KEYCLOAK_DB_DATABASE}'
      POSTGRES_USER: '${KEYCLOAK_DB_USER}'
      POSTGRES_PASSWORD: '${KEYCLOAK_DB_PASSWORD}'
    volumes:
      - 'auth_pg_data:/var/lib/postgresql/data'
    networks:
      - lamassu-net
    depends_on:
      - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'
    

  enroller:
    build:
     context: https://github.com/lamassuiot/enroller.git#develop
     dockerfile: Dockerfile.enroller
    environment:
      ENROLLER_PORT: '${ENROLLER_PORT}'
      ENROLLER_HOMEPATH: '${ENROLLER_HOMEPATH}'

      ENROLLER_POSTGRESDB: '${ENROLLER_POSTGRESDB}'
      ENROLLER_POSTGRESUSER: '${ENROLLER_POSTGRESUSER}'
      ENROLLER_POSTGRESPASSWORD: '${ENROLLER_POSTGRESPASSWORD}'
      ENROLLER_POSTGRESHOSTNAME: '${ENROLLER_POSTGRESHOSTNAME}'
      ENROLLER_POSTGRESPORT: '${ENROLLER_POSTGRESPORT}'
      ENROLLER_KEYCLOAKHOSTNAME: '${KEYCLOAK_HOSTNAME}'
      ENROLLER_KEYCLOAKPORT: '${KEYCLOAK_HTTPS_PORT}'
      ENROLLER_KEYCLOAKREALM: '${KEYCLOAK_REALM}'
      ENROLLER_KEYCLOAKPROTOCOL: '${KEYCLOAK_PROTOCOL}'
      ENROLLER_KEYCLOAKCA: '${ENROLLER_KEYCLOAKCA}'

      #ENROLLER_ENROLLERUIPROTOCOL: '${ENROLLER_UIPROTOCOL}'
      #ENROLLER_ENROLLERUIHOST: '${ENROLLER_UIHOST}'
      #ENROLLER_ENROLLERUIPORT: '${ENROLLER_UIPORT}'

      ENROLLER_CACERTFILE: '${ENROLLER_CACERTFILE}'
      ENROLLER_CAKEYFILE: '${ENROLLER_CAKEYFILE}'
      ENROLLER_CERTFILE: '${ENROLLER_CERTFILE}'
      ENROLLER_KEYFILE: '${ENROLLER_KEYFILE}'
      ENROLLER_OCSPSERVER: '${ENROLLER_OCSPSERVER}'
      ENROLLER_CONSULPROTOCOL: '${CONSUL_PROTOCOL}'
      ENROLLER_CONSULHOST: '${CONSUL_HOST}'
      ENROLLER_CONSULPORT: '${CONSUL_HTTPS_PORT}'
      ENROLLER_CONSULCA: '${ENROLLER_CONSULCA}'
      EST_SERVER: '${ENROLLER_EST_SERVER}'
      EST_APS: '${ENROLLER_EST_APS}'
      EST_EXPLICITANCHORPATH: '${ENROLLER_CA_ANCHOR_CERTFILE}'
      EST_CERTIFICATESPATH: '${ENROLLER_CERTFILE}'
      EST_PRIVATEKEYPATH: '${ENROLLER_KEYFILE}'
      JAEGER_SERVICE_NAME: '${ENROLLER_JAEGER_SERVICE_NAME}'
      JAEGER_AGENT_HOST: '${JAEGER_AGENT_HOST}'
      JAEGER_AGENT_PORT: '${JAEGER_AGENT_PORT}'
    volumes:
      - 'enroller_csr_store:${ENROLLER_HOMEPATH}'
      - './lamassu/enroller_certs:/certs'
    ports:
      - ${ENROLLER_PORT}:${ENROLLER_PORT}
    depends_on:
      - enrollerdb
      - consul-server
      - fluentd
    networks:
      - lamassu-net
    links:
      - "keycloak:keycloak.lamassu.dev"
      - "consul-server:consul.lamassu.dev"
      - "ca:ca.lamassu.dev"
      - "jaeger:jaeger.lamassu.dev"
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'
          
  enrollerdb:
    build:
     context: https://github.com/lamassuiot/enroller.git#develop
     dockerfile: Dockerfile.enrollerdb
    environment:
      POSTGRES_DB: '${ENROLLER_POSTGRESDB}'
      POSTGRES_USER: '${ENROLLER_POSTGRESUSER}'
      POSTGRES_PASSWORD: '${ENROLLER_POSTGRESPASSWORD}'
    volumes:
      - 'enroller_pg_data:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    networks:
      - lamassu-net
    depends_on:
      - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'
  ca:
    build:
       context: https://github.com/lamassuiot/lamassu-ca.git#develop
    environment:
      CA_PORT: '${CA_PORT}'
      CA_VAULTADDRESS: '${VAULT_API_ADDR}'
      CA_VAULTROLEID: '${CA_VAULTROLEID}'
      CA_VAULTSECRETID: '${CA_VAULTSECRETID}'
      CA_VAULTCA: '${CA_VAULTCA}'
      CA_CERTFILE: '${CA_CERTFILE}'
      CA_KEYFILE: '${CA_KEYFILE}'
      CA_KEYCLOAKHOSTNAME: '${KEYCLOAK_HOSTNAME}'
      CA_KEYCLOAKPORT: '${KEYCLOAK_HTTPS_PORT}'
      CA_KEYCLOAKREALM: '${KEYCLOAK_REALM}'
      CA_KEYCLOAKCA: '${CA_KEYCLOAKCA}'
      CA_KEYCLOAKPROTOCOL: '${KEYCLOAK_PROTOCOL}'
      # CA_ENROLLERUIPROTOCOL: '${ENROLLER_UIPROTOCOL}'
      # CA_ENROLLERUIHOST: '${ENROLLER_UIHOST}'
      # CA_ENROLLERUIPORT: '${ENROLLER_UIPORT}'
      CA_CONSULPROTOCOL: '${CONSUL_PROTOCOL}'
      CA_CONSULHOST: '${CONSUL_HOST}'
      CA_CONSULPORT: '${CONSUL_HTTPS_PORT}'
      CA_CONSULCA: '${CA_CONSULCA}'
      JAEGER_SERVICE_NAME: '${CA_JAEGER_SERVICE_NAME}'
      JAEGER_AGENT_HOST: '${JAEGER_AGENT_HOST}'
      JAEGER_AGENT_PORT: '${JAEGER_AGENT_PORT}'
      EST_LISTENADDR: '${CA_EST_SERVER_LISTEN_IP}:${CA_EST_SERVER_PORT}'
      EST_CERTS: '${CA_CERTFILE}'
      EST_PRIVATEKEY: '${CA_KEYFILE}'
    volumes:
      - './lamassu/ca_certs:/certs'
    networks:
      - lamassu-net
    links:
      - "vault:vault.lamassu.dev"
      - "keycloak:keycloak.lamassu.dev"
      - "consul-server:consul.lamassu.dev"
      - "jaeger:jaeger.lamassu.dev"
    ports:
      - ${CA_PORT}:${CA_PORT}
      - ${CA_EST_SERVER_PORT}:${CA_EST_SERVER_PORT}
    restart: on-failure
    depends_on:
      - consul-server
      - vault
      - fluentd
    # logging:
    #   driver: fluentd 
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'

  device-manager:
    build:
      context: https://github.com/lamassuiot/lamassu-device-manager.git#main
      dockerfile: Dockerfile.devices
    environment:
      DEVICES_PORT: '${DEVICES_PORT}'

      DEVICES_CERTFILE: '${DEVICES_CERTFILE}'
      DEVICES_KEYFILE: '${DEVICES_KEYFILE}'

      DEVICES_POSTGRESDB: '${DEVICES_POSTGRESDB}'
      DEVICES_POSTGRESUSER: '${DEVICES_POSTGRESUSER}'
      DEVICES_POSTGRESPASSWORD: '${DEVICES_POSTGRESPASSWORD}'
      DEVICES_POSTGRESHOSTNAME: '${DEVICES_POSTGRESHOST}'
      DEVICES_POSTGRESPORT: '${DEVICES_POSTGRESPORT}'

      DEVICES_KEYCLOAKPROTOCOL: '${DEVICES_KEYCLOAKPROTOCOL}'
      DEVICES_KEYCLOAKHOSTNAME: '${DEVICES_KEYCLOAKHOSTNAME}'
      DEVICES_KEYCLOAKPORT: '${DEVICES_KEYCLOAKPORT}'
      DEVICES_KEYCLOAKCA: '${DEVICES_KEYCLOAKCA}'
      DEVICES_KEYCLOAKREALM: '${DEVICES_KEYCLOAKREALM}'

      DEVICES_CONSULPROTOCOL: '${DEVICES_CONSULPROTOCOL}'
      DEVICES_CONSULHOST: '${CONSUL_HOST}'
      DEVICES_CONSULPORT: '${CONSUL_HTTPS_PORT}'
      DEVICES_CONSULCA: '${DEVICES_CONSULCA}'

      DEVICES_CACERTFILE: '${DEVICES_CACERTFILE}'
      DEVICES_CASERVERADDR: '${DEVICES_CASERVERADDR}'

      JAEGER_SERVICE_NAME: '${DEVICES_JAEGER_SERVICE_NAME}'
      JAEGER_AGENT_HOST: '${JAEGER_AGENT_HOST}'
      JAEGER_AGENT_PORT: '${JAEGER_AGENT_PORT}'
      
      #EST SERVER CONFIG
      EST_LISTENADDR: '${DEVICES_EST_SERVER_LISTEN_IP}:${DEVICES_EST_SERVER_PORT}'
      EST_CERTS: '${DEVICES_CERTFILE}'
      EST_PRIVATEKEY: '${DEVICES_KEYFILE}'

      #EST CLIENT CONFIG
      EST_SERVER: '${DEVICES_EST_SERVER}'
      # EST_APS: '${ENROLLER_EST_APS}'
      EST_EXPLICITANCHORPATH: '/certs/ca.crt'
      EST_CERTIFICATESPATH: '/certs/devices-est.crt'
      EST_PRIVATEKEYPATH: '${DEVICES_KEYFILE}'

    volumes:
      - './lamassu/device-manager_certs:/certs'
    ports:
      - ${DEVICES_PORT}:${DEVICES_PORT}
      - ${DEVICES_EST_SERVER_PORT}:${DEVICES_EST_SERVER_PORT}
    networks:
      - lamassu-net
    links:
      - "keycloak:keycloak.lamassu.dev"
      - "ca:ca.lamassu.dev"
      - "consul-server:consul.lamassu.dev"
      - "jaeger:jaeger.lamassu.dev"
    restart: on-failure
    depends_on:
      - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'

  device-manager-db:
    build:
      context: https://github.com/lamassuiot/lamassu-device-manager.git#develop
      dockerfile: Dockerfile.devicesdb
    environment:
      POSTGRES_DB: '${DEVICES_POSTGRESDB}'
      POSTGRES_USER: '${DEVICES_POSTGRESUSER}'
      POSTGRES_PASSWORD: '${DEVICES_POSTGRESPASSWORD}'
    volumes:
      - 'devices_pg_data:/var/lib/postgresql/data'
    ports:
      - 5433:5432
    networks:
      - lamassu-net
    depends_on:
      - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'

  ocsp:
    build:
      context: https://github.com/lamassuiot/GOCSP-responder.git
    environment:
      RESPONDER_FILE_CA: '${RESPONDER_FILE_CA}'
      RESPONDER_KEY: '${RESPONDER_KEY}'
      RESPONDER_CERT: '${RESPONDER_CERT}'
      RESPONDER_DB_NAME: '${ENROLLER_POSTGRESDB}'
      RESPONDER_DB_USER: '${ENROLLER_POSTGRESUSER}'
      RESPONDER_DB_PASSWORD: '${ENROLLER_POSTGRESPASSWORD}'
      RESPONDER_DB_HOST: '${ENROLLER_POSTGRESHOSTNAME}'
      RESPONDER_DB_PORT: '${ENROLLER_POSTGRESPORT}'
      RESPONDER_PORT: '${RESPONDER_PORT}'
      RESPONDER_CONSUL_PROTOCOL: '${CONSUL_PROTOCOL}'
      RESPONDER_CONSUL_HOST: '${CONSUL_HOST}'
      RESPONDER_CONSUL_PORT: '${CONSUL_HTTPS_PORT}'
      RESPONDER_CONSUL_CA: '${RESPONDER_CONSUL_CA}'
      JAEGER_SERVICE_NAME: '${RESPONDER_JAEGER_SERVICE_NAME}'
      JAEGER_AGENT_HOST: '${JAEGER_AGENT_HOST}'
      JAEGER_AGENT_PORT: '${JAEGER_AGENT_PORT}'
    volumes:
      - './lamassu/ocsp_certs:/certs'
    networks:
      - lamassu-net
    links:
      - "consul-server:consul.lamassu.dev"
      - "jaeger:jaeger.lamassu.dev"
    restart: on-failure
    depends_on:
      - consul-server
      - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'

  prometheus:
    build:
      context: https://github.com/lamassuiot/lamassu-monitoring.git#main
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - './lamassu/prometheus_certs/consul-server.crt:/etc/prometheus/certs/consul-server.crt'
    networks:
      - lamassu-net
    links:
      - "consul-server:consul.lamassu.dev"
    depends_on:
      - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'
    
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      SPAN_STORAGE_TYPE: '${SPAN_STORAGE_TYPE}'
      ES_USERNAME: '${ELASTIC_USERNAME}'
      ES_PASSWORD: '${ELASTIC_PASSWORD}'
      ES_SERVER_URLS: '${ES_SERVER_URLS}'
      ES_TLS_ENABLED: 'true'
      ES_TLS_CA: '${ES_TLS_CA}'
      ES_TLS_CERT: '${ES_TLS_CERT}'
      ES_TLS_KEY: '${ES_TLS_KEY}'
      ES_TLS_SERVER_NAME: '${ES_TLS_SERVER_NAME}'
    volumes:
      - './lamassu/jaeger_certs:/certs'
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - lamassu-net
    links:
      - "elastic:elastic.lamassu.dev"
    depends_on: 
      - elastic
      - fluentd
    restart: on-failure
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'

  elastic:
    build:
      context: https://github.com/lamassuiot/lamassu-tracing.git#main
    environment:
      node.name: 'elastic'
      discovery.type: 'single-node'
      ELASTIC_CERTS_DIR: '/usr/share/elasticsearch/config'
      ELASTIC_USERNAME: '${ELASTIC_USERNAME}'
      ELASTIC_PASSWORD: '${ELASTIC_PASSWORD}'
    volumes:
      - 'elastic_data:/usr/share/elasticsearch/data'
      - './lamassu/elastic_certs/elastic.crt:/usr/share/elasticsearch/config/elastic.crt'
      - './lamassu/elastic_certs/elastic.key:/usr/share/elasticsearch/config/elastic.key'
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - lamassu-net
    depends_on:
      - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:${FLUENTD_PORT}
    #     fluentd-async-connect: 'true'
    #     tag: '{{.Name}}'
    
    
  fluentd:
    image: fluent/fluentd:v1.13-1
    ports:
      - ${FLUENTD_PORT}:${FLUENTD_PORT}
      - ${FLUENTD_PORT}:${FLUENTD_PORT}/udp
    volumes:
      - 'fluentd_data:/fluentd/log'
    networks:
      - lamassu-net
