version: '3'

services:
  dms-example:
    build:
        context: .
    environment:
      DOMAIN: dev.lamassu.io
      PORT: 5000
    volumes:
        - ./index.js:/app/index.js
        - ./devices-crypto-material:/app/devices-crypto-material
        - ./device-manager.crt:/app/device-manager-anchore.crt
        - ./enrolled-dms.crt:/app/enrolled-dms.crt
        - ./enrolled-dms.key:/app/enrolled-dms.key
        - ./https.crt:/app/https.crt
        - ./https.key:/app/https.key
    network_mode: "host"
    # The ports directive is ignored as the network_mode is set to 'host'
    ports:
      - 5000:5000
    restart: on-failure
    entrypoint: "node /app/index.js"

        
