version: '3'

services:
  dms-example:
    build:
        context: .
    volumes:
        - ./index.js:/app/index.js
        - ./devices-crypto-material:/app/devices-crypto-material
        - ./device-manager.crt:/app/device-manager-anchore.crt
        - ./dms.crt:/app/dms.crt
        - ./dms.key:/app/dms.key
    network_mode: "host"
    ports:
      - 5000:5000
    entrypoint: "node /app/index.js"

        
